---
- hosts: servers
  become: true
  become_user: root
  become_method: sudo
  vars:
    ansible_become_pass: "{{ root_password }}"

  tasks:
    - name: Upgrade all package
      apt:
        update_cache: yes
    - name: Upgrade packages
      apt:
        upgrade: yes